// <auto-generated />
namespace Repositories
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NEW_CHANGES : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NEW_CHANGES));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041629443_NEW_CHANGES"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
