// <auto-generated />
namespace Repositories
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD_VARIABLE_DESCRIPTION_TO_NS_TBLVARIABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_VARIABLE_DESCRIPTION_TO_NS_TBLVARIABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061308150_ADD_VARIABLE_DESCRIPTION_TO_NS_TBLVARIABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
