// <auto-generated />
namespace Repositories
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD_ASSESSMENT_TYPE_ID_COLUMN_TO_ANSWERxASSESSMENT_TBL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_ASSESSMENT_TYPE_ID_COLUMN_TO_ANSWERxASSESSMENT_TBL));
        
        string IMigrationMetadata.Id
        {
            get { return "201709290411163_ADD_ASSESSMENT_TYPE_ID_COLUMN_TO_ANSWERxASSESSMENT_TBL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
