// <auto-generated />
namespace Repositories
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REMOVE_SAMLIVE_COLUMN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REMOVE_SAMLIVE_COLUMN));
        
        string IMigrationMetadata.Id
        {
            get { return "201708301726384_REMOVE_SAMLIVE_COLUMN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
