// <auto-generated />
namespace Repositories
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SAM360_FIELDS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SAM360_FIELDS));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161525041_SAM360_FIELDS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
