// <auto-generated />
namespace SOMSightRepositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD_COMPANY_NAME_AND_COMPANY_CONTACT_FIELD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_COMPANY_NAME_AND_COMPANY_CONTACT_FIELD));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031913297_ADD_COMPANY_NAME_AND_COMPANY_CONTACT_FIELD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
