// <auto-generated />
namespace SOMSightRepositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD_CHANGE_PASS_FIELD_TO_USER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_CHANGE_PASS_FIELD_TO_USER));
        
        string IMigrationMetadata.Id
        {
            get { return "201709301406194_ADD_CHANGE_PASS_FIELD_TO_USER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
