//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.AssessmentExternalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblAssessmentType", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblAssessmentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndustryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsIndustryInsightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorDescriptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconName {
            get {
                return this.IconNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IconNameField, value) != true)) {
                    this.IconNameField = value;
                    this.RaisePropertyChanged("IconName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndustryId {
            get {
                return this.IndustryIdField;
            }
            set {
                if ((this.IndustryIdField.Equals(value) != true)) {
                    this.IndustryIdField = value;
                    this.RaisePropertyChanged("IndustryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsIndustryInsights {
            get {
                return this.IsIndustryInsightsField;
            }
            set {
                if ((this.IsIndustryInsightsField.Equals(value) != true)) {
                    this.IsIndustryInsightsField = value;
                    this.RaisePropertyChanged("IsIndustryInsights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorDescriptionId {
            get {
                return this.TranslatorAdministratorDescriptionIdField;
            }
            set {
                if ((this.TranslatorAdministratorDescriptionIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorDescriptionIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorDescriptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorId {
            get {
                return this.TranslatorAdministratorIdField;
            }
            set {
                if ((this.TranslatorAdministratorIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblAssessmentQuestion", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblAssessmentQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.AssessmentExternalService.NS_TblAssessmentQuestionOption[] AssessmentQuestionOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.AssessmentExternalService.NS_TblAssessmentQuestionOption[] AssessmentQuestionOptions {
            get {
                return this.AssessmentQuestionOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessmentQuestionOptionsField, value) != true)) {
                    this.AssessmentQuestionOptionsField = value;
                    this.RaisePropertyChanged("AssessmentQuestionOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentTypeId {
            get {
                return this.AssessmentTypeIdField;
            }
            set {
                if ((this.AssessmentTypeIdField.Equals(value) != true)) {
                    this.AssessmentTypeIdField = value;
                    this.RaisePropertyChanged("AssessmentTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorId {
            get {
                return this.TranslatorAdministratorIdField;
            }
            set {
                if ((this.TranslatorAdministratorIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblAssessmentQuestionOption", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblAssessmentQuestionOption : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentQuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaturityLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentQuestionId {
            get {
                return this.AssessmentQuestionIdField;
            }
            set {
                if ((this.AssessmentQuestionIdField.Equals(value) != true)) {
                    this.AssessmentQuestionIdField = value;
                    this.RaisePropertyChanged("AssessmentQuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaturityLevelId {
            get {
                return this.MaturityLevelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MaturityLevelIdField, value) != true)) {
                    this.MaturityLevelIdField = value;
                    this.RaisePropertyChanged("MaturityLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorId {
            get {
                return this.TranslatorAdministratorIdField;
            }
            set {
                if ((this.TranslatorAdministratorIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblRecommendation", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblRecommendation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentQuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentTypeTranslationAdministrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaturityLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorNameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorTextIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentQuestionId {
            get {
                return this.AssessmentQuestionIdField;
            }
            set {
                if ((this.AssessmentQuestionIdField.Equals(value) != true)) {
                    this.AssessmentQuestionIdField = value;
                    this.RaisePropertyChanged("AssessmentQuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentTypeId {
            get {
                return this.AssessmentTypeIdField;
            }
            set {
                if ((this.AssessmentTypeIdField.Equals(value) != true)) {
                    this.AssessmentTypeIdField = value;
                    this.RaisePropertyChanged("AssessmentTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentTypeTranslationAdministrationId {
            get {
                return this.AssessmentTypeTranslationAdministrationIdField;
            }
            set {
                if ((this.AssessmentTypeTranslationAdministrationIdField.Equals(value) != true)) {
                    this.AssessmentTypeTranslationAdministrationIdField = value;
                    this.RaisePropertyChanged("AssessmentTypeTranslationAdministrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaturityLevelId {
            get {
                return this.MaturityLevelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MaturityLevelIdField, value) != true)) {
                    this.MaturityLevelIdField = value;
                    this.RaisePropertyChanged("MaturityLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorNameId {
            get {
                return this.TranslatorAdministratorNameIdField;
            }
            set {
                if ((this.TranslatorAdministratorNameIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorNameIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorNameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorTextId {
            get {
                return this.TranslatorAdministratorTextIdField;
            }
            set {
                if ((this.TranslatorAdministratorTextIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorTextIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorTextId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblMaturityLevel", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblMaturityLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaturityLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslatorAdministratorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaturityLevelId {
            get {
                return this.MaturityLevelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MaturityLevelIdField, value) != true)) {
                    this.MaturityLevelIdField = value;
                    this.RaisePropertyChanged("MaturityLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslatorAdministratorId {
            get {
                return this.TranslatorAdministratorIdField;
            }
            set {
                if ((this.TranslatorAdministratorIdField.Equals(value) != true)) {
                    this.TranslatorAdministratorIdField = value;
                    this.RaisePropertyChanged("TranslatorAdministratorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssessmentExternalService.IAssessmentServices")]
    public interface IAssessmentServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentTypes", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentTypesResponse")]
        Services.AssessmentExternalService.NS_TblAssessmentType[] GetAssessmentTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentTypes", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentTypesResponse")]
        System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblAssessmentType[]> GetAssessmentTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentQuestions", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentQuestionsResponse")]
        Services.AssessmentExternalService.NS_TblAssessmentQuestion[] GetAssessmentQuestions(int pAssessmentTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentQuestions", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentQuestionsResponse")]
        System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblAssessmentQuestion[]> GetAssessmentQuestionsAsync(int pAssessmentTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentRecommendations", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentRecommendationsResponse")]
        Services.AssessmentExternalService.NS_TblRecommendation[] GetAssessmentRecommendations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentRecommendations", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentRecommendationsResponse")]
        System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblRecommendation[]> GetAssessmentRecommendationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentMaturityLevels", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentMaturityLevelsResponse")]
        Services.AssessmentExternalService.NS_TblMaturityLevel[] GetAssessmentMaturityLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetAssessmentMaturityLevels", ReplyAction="http://tempuri.org/IAssessmentServices/GetAssessmentMaturityLevelsResponse")]
        System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblMaturityLevel[]> GetAssessmentMaturityLevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetActiveAssessmentCount", ReplyAction="http://tempuri.org/IAssessmentServices/GetActiveAssessmentCountResponse")]
        int GetActiveAssessmentCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssessmentServices/GetActiveAssessmentCount", ReplyAction="http://tempuri.org/IAssessmentServices/GetActiveAssessmentCountResponse")]
        System.Threading.Tasks.Task<int> GetActiveAssessmentCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssessmentServicesChannel : Services.AssessmentExternalService.IAssessmentServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssessmentServicesClient : System.ServiceModel.ClientBase<Services.AssessmentExternalService.IAssessmentServices>, Services.AssessmentExternalService.IAssessmentServices {
        
        public AssessmentServicesClient() {
        }
        
        public AssessmentServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssessmentServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssessmentServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssessmentServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Services.AssessmentExternalService.NS_TblAssessmentType[] GetAssessmentTypes() {
            return base.Channel.GetAssessmentTypes();
        }
        
        public System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblAssessmentType[]> GetAssessmentTypesAsync() {
            return base.Channel.GetAssessmentTypesAsync();
        }
        
        public Services.AssessmentExternalService.NS_TblAssessmentQuestion[] GetAssessmentQuestions(int pAssessmentTypeId) {
            return base.Channel.GetAssessmentQuestions(pAssessmentTypeId);
        }
        
        public System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblAssessmentQuestion[]> GetAssessmentQuestionsAsync(int pAssessmentTypeId) {
            return base.Channel.GetAssessmentQuestionsAsync(pAssessmentTypeId);
        }
        
        public Services.AssessmentExternalService.NS_TblRecommendation[] GetAssessmentRecommendations() {
            return base.Channel.GetAssessmentRecommendations();
        }
        
        public System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblRecommendation[]> GetAssessmentRecommendationsAsync() {
            return base.Channel.GetAssessmentRecommendationsAsync();
        }
        
        public Services.AssessmentExternalService.NS_TblMaturityLevel[] GetAssessmentMaturityLevels() {
            return base.Channel.GetAssessmentMaturityLevels();
        }
        
        public System.Threading.Tasks.Task<Services.AssessmentExternalService.NS_TblMaturityLevel[]> GetAssessmentMaturityLevelsAsync() {
            return base.Channel.GetAssessmentMaturityLevelsAsync();
        }
        
        public int GetActiveAssessmentCount() {
            return base.Channel.GetActiveAssessmentCount();
        }
        
        public System.Threading.Tasks.Task<int> GetActiveAssessmentCountAsync() {
            return base.Channel.GetActiveAssessmentCountAsync();
        }
    }
}
