//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.TranslatorExternalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslatorFileModel", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class TranslatorFileModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyLeadsTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForDeveloperUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApplyLeadsTemplate {
            get {
                return this.ApplyLeadsTemplateField;
            }
            set {
                if ((this.ApplyLeadsTemplateField.Equals(value) != true)) {
                    this.ApplyLeadsTemplateField = value;
                    this.RaisePropertyChanged("ApplyLeadsTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForDeveloperUse {
            get {
                return this.IsForDeveloperUseField;
            }
            set {
                if ((this.IsForDeveloperUseField.Equals(value) != true)) {
                    this.IsForDeveloperUseField = value;
                    this.RaisePropertyChanged("IsForDeveloperUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextIdentifier {
            get {
                return this.TextIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.TextIdentifierField, value) != true)) {
                    this.TextIdentifierField = value;
                    this.RaisePropertyChanged("TextIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslatedText {
            get {
                return this.TranslatedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) {
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslatorExternalService.ITranslatorServices")]
    public interface ITranslatorServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/TranslatorFileModel", ReplyAction="http://tempuri.org/ITranslatorServices/TranslatorFileModelResponse")]
        Services.TranslatorExternalService.TranslatorFileModel[] TranslatorFileModel(int pLanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/TranslatorFileModel", ReplyAction="http://tempuri.org/ITranslatorServices/TranslatorFileModelResponse")]
        System.Threading.Tasks.Task<Services.TranslatorExternalService.TranslatorFileModel[]> TranslatorFileModelAsync(int pLanguageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslatorServicesChannel : Services.TranslatorExternalService.ITranslatorServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslatorServicesClient : System.ServiceModel.ClientBase<Services.TranslatorExternalService.ITranslatorServices>, Services.TranslatorExternalService.ITranslatorServices {
        
        public TranslatorServicesClient() {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Services.TranslatorExternalService.TranslatorFileModel[] TranslatorFileModel(int pLanguageId) {
            return base.Channel.TranslatorFileModel(pLanguageId);
        }
        
        public System.Threading.Tasks.Task<Services.TranslatorExternalService.TranslatorFileModel[]> TranslatorFileModelAsync(int pLanguageId) {
            return base.Channel.TranslatorFileModelAsync(pLanguageId);
        }
    }
}
