//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOMSightServices.TranslatorExternalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslatorFileModel", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class TranslatorFileModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyLeadsTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForDeveloperUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApplyLeadsTemplate {
            get {
                return this.ApplyLeadsTemplateField;
            }
            set {
                if ((this.ApplyLeadsTemplateField.Equals(value) != true)) {
                    this.ApplyLeadsTemplateField = value;
                    this.RaisePropertyChanged("ApplyLeadsTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForDeveloperUse {
            get {
                return this.IsForDeveloperUseField;
            }
            set {
                if ((this.IsForDeveloperUseField.Equals(value) != true)) {
                    this.IsForDeveloperUseField = value;
                    this.RaisePropertyChanged("IsForDeveloperUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextIdentifier {
            get {
                return this.TextIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.TextIdentifierField, value) != true)) {
                    this.TextIdentifierField = value;
                    this.RaisePropertyChanged("TextIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslatedText {
            get {
                return this.TranslatedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) {
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_tblTranslatorLanguage", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_tblTranslatorLanguage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlagPath {
            get {
                return this.FlagPathField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagPathField, value) != true)) {
                    this.FlagPathField = value;
                    this.RaisePropertyChanged("FlagPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class ProcessResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails {
            get {
                return this.MessageDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDetailsField, value) != true)) {
                    this.MessageDetailsField = value;
                    this.RaisePropertyChanged("MessageDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessResults {
            get {
                return this.ProcessResultsField;
            }
            set {
                if ((this.ProcessResultsField.Equals(value) != true)) {
                    this.ProcessResultsField = value;
                    this.RaisePropertyChanged("ProcessResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_tblTranslatorLanguageDropDown", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_tblTranslatorLanguageDropDown : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlagPath {
            get {
                return this.FlagPathField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagPathField, value) != true)) {
                    this.FlagPathField = value;
                    this.RaisePropertyChanged("FlagPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblTranslatorAdministrator", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblTranslatorAdministrator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyLeadsTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultTextValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForDeveloperUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApplyLeadsTemplate {
            get {
                return this.ApplyLeadsTemplateField;
            }
            set {
                if ((this.ApplyLeadsTemplateField.Equals(value) != true)) {
                    this.ApplyLeadsTemplateField = value;
                    this.RaisePropertyChanged("ApplyLeadsTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultTextValue {
            get {
                return this.DefaultTextValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultTextValueField, value) != true)) {
                    this.DefaultTextValueField = value;
                    this.RaisePropertyChanged("DefaultTextValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForDeveloperUse {
            get {
                return this.IsForDeveloperUseField;
            }
            set {
                if ((this.IsForDeveloperUseField.Equals(value) != true)) {
                    this.IsForDeveloperUseField = value;
                    this.RaisePropertyChanged("IsForDeveloperUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextIdentifier {
            get {
                return this.TextIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.TextIdentifierField, value) != true)) {
                    this.TextIdentifierField = value;
                    this.RaisePropertyChanged("TextIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS_TblTranslationXLanguage", Namespace="http://schemas.datacontract.org/2004/07/SharedEntities")]
    [System.SerializableAttribute()]
    public partial class NS_TblTranslationXLanguage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslationAdministrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslationTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((this.CreatedByIdField.Equals(value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslationAdministrationId {
            get {
                return this.TranslationAdministrationIdField;
            }
            set {
                if ((this.TranslationAdministrationIdField.Equals(value) != true)) {
                    this.TranslationAdministrationIdField = value;
                    this.RaisePropertyChanged("TranslationAdministrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslationText {
            get {
                return this.TranslationTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationTextField, value) != true)) {
                    this.TranslationTextField = value;
                    this.RaisePropertyChanged("TranslationText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedById {
            get {
                return this.UpdatedByIdField;
            }
            set {
                if ((this.UpdatedByIdField.Equals(value) != true)) {
                    this.UpdatedByIdField = value;
                    this.RaisePropertyChanged("UpdatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslatorExternalService.ITranslatorServices")]
    public interface ITranslatorServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/TranslatorFileModel", ReplyAction="http://tempuri.org/ITranslatorServices/TranslatorFileModelResponse")]
        SOMSightServices.TranslatorExternalService.TranslatorFileModel[] TranslatorFileModel(int pLanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/TranslatorFileModel", ReplyAction="http://tempuri.org/ITranslatorServices/TranslatorFileModelResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.TranslatorFileModel[]> TranslatorFileModelAsync(int pLanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslatorLanguageDropDown", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslatorLanguageDropDownResponse")]
        SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguageDropDown[] GetTranslatorLanguageDropDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslatorLanguageDropDown", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslatorLanguageDropDownResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguageDropDown[]> GetTranslatorLanguageDropDownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorAdministratorResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorAdministratorResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorAdministratorResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorAdministratorResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorAdministratorResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorAdministratorResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslatorAdministratorResponse")]
        SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator[] GetTranslatorAdministrator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslatorAdministrator", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslatorAdministratorResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator[]> GetTranslatorAdministratorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorXLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/CreateTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/CreateTranslatorXLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorXLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/UpdateTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/UpdateTranslatorXLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorXLanguageResponse")]
        SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/DeleteTranslatorXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/DeleteTranslatorXLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslationXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslationXLanguageResponse")]
        SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage[] GetTranslationXLanguage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorServices/GetTranslationXLanguage", ReplyAction="http://tempuri.org/ITranslatorServices/GetTranslationXLanguageResponse")]
        System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage[]> GetTranslationXLanguageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslatorServicesChannel : SOMSightServices.TranslatorExternalService.ITranslatorServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslatorServicesClient : System.ServiceModel.ClientBase<SOMSightServices.TranslatorExternalService.ITranslatorServices>, SOMSightServices.TranslatorExternalService.ITranslatorServices {
        
        public TranslatorServicesClient() {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOMSightServices.TranslatorExternalService.TranslatorFileModel[] TranslatorFileModel(int pLanguageId) {
            return base.Channel.TranslatorFileModel(pLanguageId);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.TranslatorFileModel[]> TranslatorFileModelAsync(int pLanguageId) {
            return base.Channel.TranslatorFileModelAsync(pLanguageId);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.CreateTranslatorLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.CreateTranslatorLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.UpdateTranslatorLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.UpdateTranslatorLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorLanguage(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.DeleteTranslatorLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorLanguageAsync(SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguage pModel) {
            return base.Channel.DeleteTranslatorLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguageDropDown[] GetTranslatorLanguageDropDown() {
            return base.Channel.GetTranslatorLanguageDropDown();
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_tblTranslatorLanguageDropDown[]> GetTranslatorLanguageDropDownAsync() {
            return base.Channel.GetTranslatorLanguageDropDownAsync();
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.CreateTranslatorAdministrator(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.CreateTranslatorAdministratorAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.UpdateTranslatorAdministrator(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.UpdateTranslatorAdministratorAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorAdministrator(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.DeleteTranslatorAdministrator(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorAdministratorAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator pModel) {
            return base.Channel.DeleteTranslatorAdministratorAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator[] GetTranslatorAdministrator() {
            return base.Channel.GetTranslatorAdministrator();
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_TblTranslatorAdministrator[]> GetTranslatorAdministratorAsync() {
            return base.Channel.GetTranslatorAdministratorAsync();
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult CreateTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.CreateTranslatorXLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> CreateTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.CreateTranslatorXLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult UpdateTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.UpdateTranslatorXLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> UpdateTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.UpdateTranslatorXLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.ProcessResult DeleteTranslatorXLanguage(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.DeleteTranslatorXLanguage(pModel);
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.ProcessResult> DeleteTranslatorXLanguageAsync(SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage pModel) {
            return base.Channel.DeleteTranslatorXLanguageAsync(pModel);
        }
        
        public SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage[] GetTranslationXLanguage() {
            return base.Channel.GetTranslationXLanguage();
        }
        
        public System.Threading.Tasks.Task<SOMSightServices.TranslatorExternalService.NS_TblTranslationXLanguage[]> GetTranslationXLanguageAsync() {
            return base.Channel.GetTranslationXLanguageAsync();
        }
    }
}
